import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const nunito = localFont({
  src: './fonts/Nunito-VariableFont_wght.ttf',
  variable: '--font-nunito',
  weight: '400 500 600 700 800 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable}`}>
        <main className="min-h-screen">{children}</main>
      </body>
    </html>
  );
}
